### ISSUE TITLE
Android - doesn't work with python3-zeroconf

### ISSUE THREAD

**Issue by SrMouraSilva** [becvert/cordova-plugin-zeroconf#26] opened 2017-02-19 02:58 UTC
Python zeroconf is a _Pure Python Multicast DNS Service Discovery Library (Bonjour/Avahi compatible)_ https://pypi.python.org/pypi/zeroconf

`cordova-plugin-zeroconf` can't discover (watch) a Python zeroconf service, but the reverse works.

Sorry for the description of the error, I do not know what the cause of it would be. If you can quote how can I help ...

**Comment by becvert** [comment] 2017-02-19 09:53
Can you show how you call `wsserver.watch`?
And how you register your service in Python?
Thanks

**Comment by SrMouraSilva** [comment] 2017-02-19 15:15
Watch:
https://github.com/PedalPi/Apk/blob/1fedfdd2223a7c18bd48dba0b9303e8f7cce4962/src/pages/configurations/configurations.ts#L43

Python service
https://github.com/PedalPi/WebService/blob/b63bfc916948a2fb11f822751beb1e7c90677c94/zeroconf/server.py#L13

Observation:
* The cordova-plugin-zeroconf works with my dlink router 
* The cordova-plugin-zeroconf works with [python pybonjour3](https://github.com/depl0y/pybonjour-python3) with avahi (apt-get install libavahi-compat-libdnssd1)

**Comment by becvert** [comment] 2017-02-20 12:19
Are you saying all is fine with this other python library, i.e. pybonjour3?

Looks to me that Python side you're registering your service on a loopback address `socket.inet_aton("127.0.0.1")`?
Could you try on another interface and one that supports multicast instead?

**Comment by SrMouraSilva** [comment] 2017-02-20 18:19
> Are you saying all is fine with this other python library, i.e. pybonjour3?

Yes

> Looks to me that Python side you're registering your service on a loopback address socket.inet_aton("127.0.0.1")?

This really does not make much sense. I followed the [example](https://github.com/jstasiak/python-zeroconf/blob/master/examples/registration.py) and did not mind. 

> Could you try on another interface and one that supports multicast instead?

I tested in a PC with cable and in a notebook with wi-fi. 

**I will try again with an not IP loopback**

Thanks

**Comment by becvert** [comment] 2017-02-21 07:58
Let us know the result of you last try and then close this issue please as the problem is not with this plugin.

**Closed** 2017-03-03 07:45 UTC

**Comment by SrMouraSilva** [comment] 2017-05-13 20:16
Hello, I'm sorry for the delay in replying.

I did some more tests and found that the problem was possibly in the configuration. The host in `python-zeroconf` must be the IP of the machine on the network where the other devices will be connected. So the other devices will be able to locate the machine.
