### ISSUE TITLE
[Android] zeroconf.watch event with service without ipv4Addresses 

### ISSUE THREAD

**Issue by EnricoGiordano1992** [becvert/cordova-plugin-zeroconf#49] opened 2017-10-12 07:46 UTC
Hi becvert,
I've a problem using your plugin with Android device. In particular, I receive, on "watch", event without ipv4Addresses; at first call, I can simply check if service does not contain ipv4Addresses (because I receive duplicate service, one with ipv4Addresses, one without ipv4Addresses). When I go out and return in a app page that use zeroconf, it returns only service without ipv4Addresses. How can I resolve this? This is my code:

```
  ionViewDidLoad(){
    var self = this;
    this.platform.ready().then(() =>{
      if((<any>window).cordova && (<any>window).cordova.plugins){
        var zeroconf = (<any>window).cordova.plugins.zeroconf;
        zeroconf.registerAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
        zeroconf.watchAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
        zeroconf.watch('_myservice._tcp.', 'local.',
          function(result:any) {
            var exists_name = false;
            for(var i = 0; i < self.List.length; i++){
              if(self.List[i].name == result.service.name)
                exists_name = true;
            }
            if(!exists_name && result.service.ipv4Addresses.length > 0){
              self.List.push(result.service);
              self.zone.run(() => { }); // update ngFor externally
            }
          },
          function(err:any){
              console.log("err: "+err)
            }
          );
        }
    })

      var self = this;
      var foo_timeout2 = true;
      setTimeout(
        function(){
          if(foo_timeout2){
            self.timeElapsed = true;
          }
      },10000);
  }

```

I'm using Ionic (3.13.0 but same problem with previous versions), tested on Samsung Galaxy S4 (Android 5.0.1) and Wiko Fever (Android 6.0).
Thanks for help!

**Comment by becvert** [comment] 2017-10-12 09:49
check that `result.action == 'resolved'`?

**Comment by EnricoGiordano1992** [comment] 2017-10-12 13:50
At first time, when plugin find a device, it gives me action == "resolved", but second time that I use it, it gives me only action == "added".

**Comment by becvert** [comment] 2017-10-12 16:56
by second time does it mean you 'paused' the app and then you resumed it? or you left if for good and then reopened it?
does `ionViewDidLoad` is call again on resume?

**Comment by EnricoGiordano1992** [comment] 2017-10-12 17:37
No, I mean that I change page the I return in the page that I call zeroconf plugin. Yes, ionViewDidLoad is called again.

**Comment by antweb** [comment] 2017-11-03 14:41
Just ran into the same problem. action == "resolved" is only returned on the first watch attempt. Any consecutive watch just returns action == "added". zeroconf.unwatch() does not seem to help. But after zeroconf.stop() I once again receive another action == "resolved".

(Android 7.1.2 / cordova-android 6.3.0)

**Comment by emcniece** [comment] 2018-04-04 04:14
We recently introduced a [reInit()](https://github.com/becvert/cordova-plugin-zeroconf#reinitsuccess-failure) method to help with situations where watches may potentially be duplicated. This method reverts the plugin almost completely to its initial state. Any chance you could try this and report the outcome?

**Comment by shader** [comment] 2018-06-19 14:22
I'm running into this problem, I think.

`reInit()` doesn't seem to help, and sometimes even reloading the app doesn't seem to change anything either... In fact, it seems that if I start my service and register it before launching the app, I only receive the "added" events without the IP addresses.

Interestingly, I only had this problem when running on the ad-hoc wifi of my android device; when both the device and my service are running on a local wifi network it seems to work just fine.

**Comment by emcniece** [comment] 2018-06-19 15:57
@shader can you _cast some light_ on your network topologies for both working and non-working scenarios?

@becvert I wonder if the OS is having trouble resolving IP addresses when using a particular network adapter configuration. Could this be caused by lack of DHCP?

**Comment by becvert** [comment] 2018-06-20 16:52
@emcniece I have no idea :confused:

**Comment by becvert** [comment] 2019-03-27 09:05
Closing old issue. Feel free to reopen.

**Closed by becvert** 2019-03-27 09:05 UTC
