### ISSUE TITLE
Failing to find a service if already running

### ISSUE THREAD

**Issue by Dinkh** [becvert/cordova-plugin-zeroconf#29] opened 2017-03-13 09:33 UTC
Hi there,

thanks for the great plugin.

I am using Tuneblade (PC) and trying to find the Tuneblade service (from Android).
But the service only shows up if I start Tuneblade (PC) after I start zeroconf.watch (Android)

Further I saw the other bugs and it takes at least 20 seconds for the first device to show up.

For me it would be good enough to have a zeroconf.list to show all currently registered devices (not sure if zeroconf supports this).

**Comment by becvert** [comment] 2017-03-14 07:44
Hi.
I'll have a look into that but not before some time.
Thanks

**Comment by becvert** [comment] 2017-04-20 16:14
I cannot reproduce the issue with my tests.
Please try with a service other than tuneblade to see if it happens too.

zeroconf.watch should already be listing the registered devices.

closing for now as I cannot do more.
Feel free to dig into the code. Thank you.

**Closed by becvert** 2017-04-20 16:14 UTC
