### ISSUE TITLE
Why do you install 3d party plugging that mess up our files

### ISSUE THREAD

**Issue by julientype** [becvert/cordova-plugin-zeroconf#90] opened 2020-08-29 00:21 UTC
plugins are java api to one java-script to control it by one file hook not ,,,,,node modules...   
Stay out out of our  cordova  file folders.....

**Comment by emcniece** [comment] 2020-08-29 01:07
Closing as duplicate of https://github.com/becvert/cordova-plugin-zeroconf/issues/91

**Closed by emcniece** 2020-08-29 01:07 UTC
